name: timemachine
services:
  timemachine:
    hostname: timemachine
    networks:
      timemachine:
        ipv4_address: 10.1.1.10
    environment:
      - TM_USERNAME=timemachine
      - TM_GROUPNAME=timemachine
      - PASSWORD=timemachine
      - TM_UID=1000
      - TM_GID=1000
      - SET_PERMISSIONS=false
      - SHARE_NAME=TimeMachineWDMP
      - VOLUME_SIZE_LIMIT=0
      - WORKGROUP=WORKGROUP-TM
    restart: unless-stopped
    volumes:
      - /mnt/time_machine:/opt/timemachine
    tmpfs:
      - /run/samba
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    container_name: timemachine
    image: mbentley/timemachine:smb

networks:
  timemachine:
    driver: ipvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 10.1.0.0/21
          gateway: 10.1.0.1
